# Generated by Django 4.2 on 2024-10-31 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='app.team')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('wing', 'Kanat'), ('body', 'Gövde'), ('tail', 'Kuyruk'), ('avionics', 'Aviyonik')], max_length=20)),
                ('aircraft_type', models.CharField(choices=[('tb2', 'TB2'), ('tb3', 'TB3'), ('akinci', 'AKINCI'), ('kizilelma', 'KIZILELMA')], max_length=20)),
                ('status', models.CharField(default='available', max_length=10)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='app.team')),
            ],
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tb2', 'TB2'), ('tb3', 'TB3'), ('akinci', 'AKINCI'), ('kizilelma', 'KIZILELMA')], max_length=20)),
                ('assembled', models.BooleanField(default=False)),
                ('parts', models.ManyToManyField(related_name='aircrafts', to='app.part')),
            ],
        ),
    ]
